### ISSUE TITLE
Add option for admins to archive organization templates

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#1108]
We have a field for this in the database already, but it would be nice to surface it w/ a delete button (w/ confirmation modal), presumably on either the organization home screen or the organization admin screen.

**Comment by rachelekm** [comment]
@jfrankl do you have any input on where this delete button should go/look like? In my mind there's an "x" delete button in the top righthand corner for each template (that only appears for admins) on the organization home screen and I can follow the same confirmation modal design as when deleting a map on the "My Maps" page.

**Comment by jfrankl** [comment]
@rachelekm thank you for checking in. Instead of an "x" delete button, I'd do the same pattern as on the "My Maps" page with the "..." button that opens a flyout with an option to delete. Deleting a template is an uncommon action, so I think tucking it away like that would be the best balance.

Using the same confirmation modal as when deleting a map sounds perfect.
