### ISSUE TITLE
Add docs for working with the data processing scripts

### ISSUE THREAD

**Issue by aaronxsu** [PublicMapping/districtbuilder#1242]
Inviting @maurizi to add more details or to-dos here.

**Comment by nlagrone** [comment]
Adding context and steps to follow for running through data processing scripts in the repo.

**Comment by lukemckinstry** [comment]
more context from @maurizi: this issue is meant to address a concern of Micah Altmans that we don't have any documentation on the data format of the GeoJSON that feeds into those scripts. The overall goal is essentially “if an outside organization wants to spin up DistrictBuilder and provide their own data, they know how to do so from reading the docs”. our scripts are documented assuming you have input data in the correct format already - but we never explain what that format is anywhere.
