### ISSUE TITLE
Calculate sidebar updates in real-time as rectangle tool is dragged

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/districtbuilder#219]
## Overview

In the prototype, the sidebar updates in real-time with the pending rectangular selection. In our app, the sidebar only updates after the user completes their rectangular selection. We would like this to behave in a similar manner as the prototype. However, there are some additional considerations to account for, since we are dealing with a more complicated set of calculations than the prototype needs. Because of this, we expect that a naive approach here would result in sluggish behavior as many potentially hefty calculations will be triggered in quick succession. An approach to improve the user experience may involve something such as the following:
 1) Debounce the calculation requests
 2) Make use of web workers to ensure the user experience doesn't suffer as a calculation is churning

## Acceptance criteria

The sidebar is updating in real-time as the rectangle tool is dragged. And there is no major UI sluggishness resulting from this change.

**Comment by pcaisse** [comment]
We might also refactor the [getDemographics](https://github.com/PublicMapping/districtbuilder/blob/develop/src/shared/functions.ts#L28-L47) function to use a good ol' fashioned `for` loop since they look to be much faster than `reduce`: https://jsperf.com/foreach-vs-reduce-vs-for-loop

**Comment by jfrankl** [comment]
In case it's useful, here is how I handled this on the prototype.

When a user clicks on a geounit or finishes drawing a rectangle over geounits, I called those geounited `selected`. When a user is midway through drawing a rectangle, any of those geounits I call `highlighted`.

Before the user begins drawing a rectangle, I already have the population totals for each district. When the user is drawing a rectangle, I only care about the those highlighted geounits. For each of the highlighted geounits, what district was it in before and where is it going?

**Example**

A user is working on District 8. They have highlighted the following three geounits

Geounit 1: assigned to district 3
Geounit 2: assigned to district 8
Geounit 3: assigned to district 2

To calculate the populations of the districts that reflect these highlighted geounits, I would subtract the population of Geounit 1 from District 3's total, subtract the population of Geounit 3 from District 2's total, and add the population of Geounit 1 and Geounit 3 to District 8. For Geounit 2, I wouldn't do anything because it's basically going from District 8 to District 8.

I use `debounce` on the function that gets the geounits from under the rectangle.

I memoize the function that calculates these changes to prevent it from recalculating this with the same input. I think this method is the least important of the three I mentioned.
