### ISSUE TITLE
Demographic labels don't show up for PA blockgroups

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/districtbuilder#255]
## Overview

For some reason, demographic labels are not showing up for blockgroups in PA. All other labels are showing up correctly (PA - counties, blocks; DE - counties, tracts, blocks).

## Acceptance criteria

Demogaphic labels are being displayed for PA blockgroups

**Comment by jfrankl** [comment]
@tgilcrest @maurizi I took a closer look at this. I suspect that this issue has to do with the tile generation process, rather than a frontend issue.

## Missing blockgroup point data

I noticed that the blockgroup labels do appear when zoomed out far, which suggests to me that there is an issue with the tiles. 
![image](https://user-images.githubusercontent.com/1809908/89933832-a9212b00-dbdd-11ea-925e-7e07d33529b3.png)

When zoomed in more, using `ogrinfo` on [various](https://global-districtbuilder-dev-us-east-1.s3.amazonaws.com/regions/US/PA/2020-07-21T18:24:08.036Z/tiles/9/144/192.pbf) [tiles](https://global-districtbuilder-dev-us-east-1.s3.amazonaws.com/regions/US/PA/2020-07-21T18:24:08.036Z/tiles/7/35/48.pbf) revealed county labels but not blockgroup labels. 

`ogrinfo https://global-districtbuilder-dev-us-east-1.s3.amazonaws.com/regions/US/PA/2020-07-21T18:24:08.036Z/tiles/9/144/192.pbf`
```
1: blockgroup (Multi Polygon)
2: countylabels (Point)
3: county (Polygon)
```

## Debugging
I replaced the text labels with red circles helps show where the points are available and where they are missing.

### County, Zoom Level 6
This looks as expected
![image](https://user-images.githubusercontent.com/1809908/89935157-b93a0a00-dbdf-11ea-9640-c18e0f979cba.png)

### Blockgroups, Zoom Level 4
One tile contains many blockgroup points, the other tile contains no blockgroup points. This looks like an issue with Tippecanoe where it is generating empty tiles because the tiles are too big. This can be overridden by the `--no-tile-size-limit`, which we might want to use, but we should also probably avoid generating tiles at this zoom level in general.
![image](https://user-images.githubusercontent.com/1809908/89935296-f2727a00-dbdf-11ea-9374-64a5746c27d5.png)

### Blockgroups, Zoom Level 6
No blockgroup points are on tiles at zoom level 6
![image](https://user-images.githubusercontent.com/1809908/89935239-dff84080-dbdf-11ea-98be-7d8763f3bc2d.png)

### Blocks, Zoom Level 12
Many of the block labels are visible, but some seem to be missing
![image](https://user-images.githubusercontent.com/1809908/89934972-67917f80-dbdf-11ea-8109-408f4d2bf48a.png)

**Comment by jfrankl** [comment]
I'm going to remove the `design` tag pass this issue back to the development team. I'd be happy to pair on this. I think it would be useful to have someone who is more familiar with the script involved.

**Comment by tgilcrest** [comment]
Thanks for writing up your findings @jfrankl. We'll have the dev team take a look at it.
