### ISSUE TITLE
Support selecting partially locked geounits

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#323]

**Comment by jfrankl** [comment]
This should work for both click or rectangle selection.

**Comment by kshepard** [comment]
Note, that due to the way we deal with blocks, I think this behavior will only really be functional at the county level -- breaking up into blockgroups. At the blockgroup level, it won't be able to work (yet), since that would entail breaking up into blocks, and thus showing them at a level where they can't be seen.

**Comment by tgilcrest** [comment]
Updating with Jeff's notes from our call:
* We don't need to fix this for Tuesday, 9/15. We can keep working on it next week
* When on county select mode, if a user clicks a county that has some locked blockgroups, we want the non-locked blockgroups in the county to be selected. If they click again, we want those selected blockgroups to become unselected.
* For blocks, we are okay with handling them differently, since they are a more advanced part of the tool.
* We should show a toast message when we are unable to make a selection due to locked blocks.
* We should throttle the message or find another way for it not to appear over and over if the user is selecting with the rectangle tool
