### ISSUE TITLE
Upgrade PostgreSQL in staging environment

### ISSUE THREAD

**Issue by hectcastro** [PublicMapping/districtbuilder#340]
Upgrade the version of PostgreSQL used in staging to align with https://github.com/PublicMapping/districtbuilder/issues/339. Ensure that any steps taken are documented so that they can be used as input to a plan for the PostgreSQL upgrade in production.

**Comment by rbreslow** [comment]
- [ ] Connect to the database instance from within the AWS network. Ensure that the session is initiated within a `tmux` session.
   ```console
   tmux new -s psql
   psql -h database.service.internal -U app -d app
   ```
- [ ] Check for any outstanding prepared transactions.
   ```sql
   SELECT count(*) FROM pg_catalog.pg_prepared_xacts;
   ```
- [ ] Ensure that usage of all `reg*` data types are removed.
   ```sql
   SELECT count(*) FROM pg_catalog.pg_class c, pg_catalog.pg_namespace n, pg_catalog.pg_attribute a 
   WHERE c.oid = a.attrelid 
      AND NOT a.attisdropped 
      AND a.atttypid IN ('pg_catalog.regproc'::pg_catalog.regtype, 
                         'pg_catalog.regprocedure'::pg_catalog.regtype, 
                         'pg_catalog.regoper'::pg_catalog.regtype, 
                         'pg_catalog.regoperator'::pg_catalog.regtype, 
                         'pg_catalog.regconfig'::pg_catalog.regtype, 
                         'pg_catalog.regdictionary'::pg_catalog.regtype) 
      AND c.relnamespace = n.oid 
      AND n.nspname NOT IN ('pg_catalog', 'information_schema');
   ```
- [ ] Ensure that any asynchronous application workflows with database access are disabled or throttled as appropriate (e.g., AWS Batch, AWS Lambda).
- [ ] Vacuum the target database.
   ```sql
   SET maintenance_work_mem='2GB';
   \timing
   VACUUM (FREEZE, ANALYZE, VERBOSE);
   ```
- [ ] Upgrade any independently versioned extensions that would prevent the upgrade from completing successfully (e.g., PostGIS). If something is missed, information about the failed precondition should be noted in `pg_upgrade_precheck.log`.
   ```sql
   ALTER EXTENSION postgis UPDATE TO 'X.Y.Z';
   ALTER EXTENSION postgis_tiger_geocoder UPDATE TO 'X.Y.Z';
   ALTER EXTENSION postgis_topology UPDATE TO 'X.Y.Z';
   ```
- [ ] Ensure a parameter group supported by the version being upgraded to exists.
- [ ] Trigger the PostgreSQL engine upgrade via the AWS console.
- [ ] Upgrade independently versioned extensions (e.g., PostGIS).
   ```sql
   ALTER EXTENSION postgis UPDATE TO 'X.Y.Z';
   ALTER EXTENSION postgis_tiger_geocoder UPDATE TO 'X.Y.Z';
   ALTER EXTENSION postgis_topology UPDATE TO 'X.Y.Z';
   ```
- [ ] Vacuum the target database, again.
   ```sql
   SET maintenance_work_mem='2GB';
   \timing
   VACUUM (FREEZE, ANALYZE, VERBOSE);
   ```
- [ ] Ensure no `autovacuum` processes are running. If so, terminate them so that they do not content with the manual `VACUUM` above.
   ```sql
   SELECT datname, usename, pid, state, wait_event, current_timestamp - xact_start AS xact_runtime, query
   FROM pg_stat_activity 
   WHERE upper(query) LIKE '%VACUUM%' 
   ORDER BY xact_start;

   SELECT pg_terminate_backend('PID');
   ```
- [ ] If necessary, reboot the RDS instance so that any out-of-sync parameter group settings take full effect.
- [ ] Ensure any PostgreSQL client libraries are upgraded to match the server version.
- [ ] Undo any application specific changes that were applied to facilitate the database upgrade.
