### ISSUE TITLE
Upgrade PostgreSQL in production environment

### ISSUE THREAD

**Issue by hectcastro** [PublicMapping/districtbuilder#341]
Use the steps enumerated in https://github.com/PublicMapping/districtbuilder/issues/340 as the inputs to produce a plan to upgrade PostgreSQL in production. Complete those steps in the production environment, ensuring that all stakeholders are communicated with as appropriate.

**Comment by rbreslow** [comment]
- [ ] Connect to the database instance from within the AWS network. Ensure that the session is initiated within a `tmux` session.

   ```console
   tmux new -s psql
   psql -h database.service.internal -U app -d app
   ```

- [ ] Check for any outstanding prepared transactions.

   ```sql
   SELECT count(*) FROM pg_catalog.pg_prepared_xacts;
   ```

- [ ] Ensure that usage of all `reg*` data types are removed.

   ```sql
   SELECT count(*) FROM pg_catalog.pg_class c, pg_catalog.pg_namespace n, pg_catalog.pg_attribute a 
   WHERE c.oid = a.attrelid 
      AND NOT a.attisdropped 
      AND a.atttypid IN ('pg_catalog.regproc'::pg_catalog.regtype, 
                         'pg_catalog.regprocedure'::pg_catalog.regtype, 
                         'pg_catalog.regoper'::pg_catalog.regtype, 
                         'pg_catalog.regoperator'::pg_catalog.regtype, 
                         'pg_catalog.regconfig'::pg_catalog.regtype, 
                         'pg_catalog.regdictionary'::pg_catalog.regtype) 
      AND c.relnamespace = n.oid 
      AND n.nspname NOT IN ('pg_catalog', 'information_schema');
   ```

- [ ] Ensure that any asynchronous application workflows with database access are disabled or throttled as appropriate (e.g., AWS Batch, AWS Lambda).

- [ ] Vacuum the target database.

   ```sql
   SET maintenance_work_mem='2GB';
   \timing
   VACUUM (FREEZE, ANALYZE, VERBOSE);
   ```

- [ ] Upgrade any independently versioned extensions that would prevent the upgrade from completing successfully (e.g., PostGIS). If something is missed, information about the failed precondition should be noted in `pg_upgrade_precheck.log`.
   
   ```sql
   SELECT * FROM pg_available_extensions WHERE name LIKE 'postgis%';
             name          | default_version | installed_version |                               comment
   ------------------------+-----------------+-------------------+---------------------------------------------------------------------
    postgis                | 2.5.2           | 2.5.2             | PostGIS geometry, geography, and raster spatial types and functions
    postgis_tiger_geocoder | 2.5.2           | 2.5.2             | PostGIS tiger geocoder and reverse geocoder
    postgis_topology       | 2.5.2           | 2.5.2             | PostGIS topology spatial types and functions
   (3 rows)
   ```

- [ ] Update the `rds_engine_version` and `rds_parameter_group_family` variables and run Terraform to ensure a parameter group supported by the version being upgraded to exists.

- [ ] Trigger the PostgreSQL engine upgrade via the AWS console.

- [ ] Run Terraform again to destroy the deposed parameter group.

- [ ] Upgrade independently versioned extensions (e.g., PostGIS).

   ```sql
   ALTER EXTENSION postgis UPDATE TO '3.0.0';
  SELECT postgis_extensions_upgrade();
   ```

- [ ] Vacuum the target database, again.

   ```sql
   SET maintenance_work_mem='2GB';
   \timing
   VACUUM (FREEZE, ANALYZE, VERBOSE);
   ```

- [ ] Ensure no `autovacuum` processes are running. If so, terminate them so that they do not content with the manual `VACUUM` above.

   ```sql
   SELECT datname, usename, pid, state, wait_event, current_timestamp - xact_start AS xact_runtime, query
   FROM pg_stat_activity 
   WHERE upper(query) LIKE '%VACUUM%' 
   ORDER BY xact_start;

   SELECT pg_terminate_backend('PID');
   ```

- [ ] If necessary, reboot the RDS instance so that any out-of-sync parameter group settings take full effect.

- [ ] Ensure any PostgreSQL client libraries are upgraded to match the server version.

   ```console
   sudo yum remove $(yum list installed | grep amzn2extra-postgresql11 | awk '{ print $1 }')
   sudo tee /etc/yum.repos.d/pgdg.repo<<EOF
   [pgdg12]
   name=PostgreSQL 12 for RHEL/CentOS 7 - x86_64
   baseurl=https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-7-x86_64
   enabled=1
   gpgcheck=0
   EOF
   sudo yum makecache
   sudo yum install postgresql12
   ```

- [ ] Undo any application specific changes that were applied to facilitate the database upgrade.

**Comment by rbreslow** [comment]
Two interesting things to note.

It doesn't look like PostGIS was installed on the DB instance. Are we actually using it in this application?

```sql
districtbuilder=> SELECT * FROM pg_available_extensions WHERE name LIKE 'postgis%';
          name          | default_version | installed_version |                               comment
------------------------+-----------------+-------------------+---------------------------------------------------------------------
 postgis                | 2.5.2           |                   | PostGIS geometry, geography, and raster spatial types and functions
 postgis_topology       | 2.5.2           |                   | PostGIS topology spatial types and functions
 postgis_tiger_geocoder | 2.5.2           |                   | PostGIS tiger geocoder and reverse geocoder
(3 rows)

Time: 31.191 ms
```

I went ahead and installed it before triggering the PostgreSQL engine upgrade.

Also, because there were Terraform changes on `develop` beyond the changes to the DB parameter group, I had to make the following modifications to `infra`:

```diff
diff --git a/scripts/infra b/scripts/infra
index 1258541..0eb1be5 100755
--- a/scripts/infra
+++ b/scripts/infra
@@ -45,6 +45,8 @@ if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

             terraform plan \
                 -var="image_tag=${GIT_COMMIT}" \
+                -target=module.database.aws_db_instance.postgresql \
+                -target=aws_db_parameter_group.default \
                 -var-file="${DB_SETTINGS_BUCKET}.tfvars" \
                 -out="${DB_SETTINGS_BUCKET}.tfplan"
             ;;
```
