### ISSUE TITLE
Styling pass: Labels dropdown

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#391]
We should style the labels dropdown to look like the prototype, so datasets from different categories are separated into different sections. We don't have "Places" yet; our categories would be "Race" and "Election"

![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/2657fc1d-e4be-4378-b325-66221a61cc0e)

**Comment by jfrankl** [comment]
@alexelash pointed out that we can use 'optgroup' with the default 'select' input to add sections to this https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_optgroup. I think that would be a good short term solution for this issue, rather than re-implementing this as a dropdown.

Long term, I imagine this feature becoming more complex and requiring a custom dropdown.
