### ISSUE TITLE
Visually distinguish locked districts in sidebar

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#432]
The locked districts are visually distinguished on the map but not in the sidebar. We should make it more clear on the sidebar that a district is locked.

**Comment by alexelash** [comment]
@jfrankl and I discussed this offline. Districts are now visually distinguished on the sidebar as well with a lock icon that is always visible. We considered making the row more obviously locked, but aren't confident that it will add to the user experience. As a result, I'm closing this issue for now. If it reappears due to user testing then we'll tackle it then, hopefully with more information to inform the design change.
