### ISSUE TITLE
Tooling to update data in place

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#456]
@kshepard could you flesh out?

**Comment by kshepard** [comment]
### Overview

DistrictBuilder data will need to be updated several times in the future (adding additional demographics, etc.), and we would like to have some tooling in place to make this straightforward. There are a couple key challenges that need to be addressed here:
 1) The initial data that has been published was not sorted by any specific value, and the sort order matters, as it's inherently used in the topological structure
 2) There are some changes that will be incompatible. E.g. if a block group shifts from one county to another. We will need to detect any incompatibilities, because we don't want to update data and have everyone's existing maps break. Note: we don't need to solve the problem of what to do with incompatible data as part of this task -- we will eventually need to create a migration strategy, but simply being able to detect it now will be good enough.

In hindsight, the easiest way to proceed would have been ordering the geounits by their ids before doing any processing. However, even in this case, we'd still need to look at the previous data to be able to detect incompatibilities. If we were to try ordering it in this manner now, we'd need a migration plan, with code that would adapt all existing plans from the old format to the new one. I would like to avoid this, as it would be hard work, and would require downtime.

After thinking about it, I'm thinking the best approach is likely the following:
 * Aim to keep the initial plans valid by using that same ordering for future updates
 * We would need to update the `process-geojson` command to accept an optional S3 URL for the existing data. The command would pull down the topology, and would sort the new data based on the sort order within this topology.
 * While this is happening, this will be the ideal time to check for data inconsistencies: if the hierarchy is different in any way, we raise an error stating what's inconsistent, and halt processing
 * The `publish-region` command will be unchanged: we will still want to publish it separately and test locally to ensure all is well before pushing to production
 * We will need a new command (`update-region`?), which is very similar to `publish-region`, except it simply uploads the data to an existing S3 URL that's specified as a parameter, and then performs no database updates (the static data is changing in-place, so no database update is needed)


### Acceptance criteria

 * The `process-geojson` command can accept an optional S3 URL for updating existing data. It will use the existing data's sort order for sorting the new data.
 * Data inconsistencies are checked for, and if any are found, an apropriate error is raised and processing is halted
 * A new `update-region` command is created to allow for pushing new data to an existing S3 URL
