### ISSUE TITLE
Configure Dane County

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#472]
We need to prep a data file for Dane County Wisconsin for their custom instance. Same as state-level data, just clipped to Dane County.

AC: 
* Filter out non-Dane County data from Wisconsin
* Configure Dane County custom region
* Attempt to configure without County level (do if minimal, write up further issues if not)
* Figure out what we need to do to support not showing block modal

**Comment by pcaisse** [comment]
Calling out some places in the frontend where we assume that block-level geounits are present and special:
* https://github.com/PublicMapping/districtbuilder/blob/develop/src/client/components/MapHeader.tsx#L93
* https://github.com/PublicMapping/districtbuilder/blob/develop/src/client/components/map/RectangleSelectionTool.ts#L268-L278

Also may be worth noting that the `getChildGeoUnits` function (https://github.com/PublicMapping/districtbuilder/blob/develop/src/client/components/map/index.ts#L341-L367) only returns direct descendants. This is fine now since we typically only have three levels -- county, blockgroup, and block -- and blocks are special so we only really use this to get the blockgroups in a county in practice. However, if we had more subdivisions of administrative units _or_ if blocks weren't special, this would cause issues.
