### ISSUE TITLE
Link to create map

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#496]
To support some clients, we want to develop a link that will route the user directly into the map drawing page. This will automatically create a map in the user's account when they follow it. Since the link will bypass the create map page, it should include parameters that define the things a user would select on the create map page, e.g. region, number of districts, etc. 

AC:
1. For a given region (project definition?) we can create a link that will route a user directly into the map drawing page.
2. Following the link automatically creates a map with the specified parameters in the user's account
3. If the user is unauthenticated, redirect them to the register page where they can create an account and be redirected to the map they are trying to create
4. If the user already has an account, allow them to switch to the Login page, where they can login and be redirected to the map they are trying to create

**Comment by kshepard** [comment]
Just to give some extra context/clarification here: the "link" being referred to would be something like e.g.: `https://app.districtbuilder.org/create-project?regionConfig=123&mapName=MyMap&numDistricts=12`. This link would be placed on a partner's website, so a user can click on it and it will automatically create a map for them and direct them to it (if they're logged in). In the example above, I used the existing `create-project` route, since I think that may be a good fit, but if we want to create a new route for this, that would also work.

**Comment by kshepard** [comment]
Note: we're discussing some changes to this. Likely it won't be using a modal, and will instead use the existing login/register page. More details to follow.
