### ISSUE TITLE
Create Dane County organization w/ templates and convert existing maps to use template

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#697]

**Comment by tgilcrest** [comment]
Completed.

Mike walked me through the first part of creating the organization and templates, and then I completed the existing map conversion on my own. I was able to do this by manually setting maps with the Dane County region config to the template we had just created. 

One thing I discovered after doing this was that, for maps created before Organizations were deployed, the new Districts jsonb field remains NULL when you do this manually. This causes the Org page to crash if you want to set any maps to Featured, because it tries to load the preview and can't. We should do a migration that updates this field for all projects; we'll write up a separate issue for that.
