### ISSUE TITLE
Show state outline on minimaps in user project list

### ISSUE THREAD

**Issue by kevinearldenny** [PublicMapping/districtbuilder#873]
## Detailed Description
A request from @jfrankl :

Do we have the outline shape available in a way that could be rendered by these mini maps? I’m noticing that for an incomplete map, it would be really nice to see the outline of the state, so it has more meaning before the drawing is complete.

**Comment by maurizi** [comment]
We have the geojson for the unassigned district available as well, we're just not assigning it a fill color or border. If we gave maybe a light gray color to the unassigned district for the minimaps the whole state would be filled in.

Otherwise, I think we could use `turf` to combine the district polygons on the frontend and derive a state outline that way.

**Comment by jfrankl** [comment]
Using the geojson for the unassigned district seems like a great idea. For a quick mockup, I just exported the geojson from DistrictBuilder, and I think it looks good with a light grey fill:

![Screen Shot 2021-07-28 at 12 38 09 AM](https://user-images.githubusercontent.com/1809908/127264707-fa83ed68-cecd-4484-88bc-6228b2ee3d54.png)
