### ISSUE TITLE
Add Organization module on Project Import screen

### ISSUE THREAD

**Issue by dmcglone** [PublicMapping/districtbuilder#971]
On the Import Project screen, there is no option to add the Project to an Organization. See the Organization module on the Create Project screen:
![image](https://user-images.githubusercontent.com/1688859/130487842-301a71bc-35a0-49e2-9da9-41817fcc60f6.png)

This should be added to the Import Project screen. The best way to do this would be to display it _after_ the block file is imported, so the user only has the option to add to an Organization that matches the Region of the block file.

**Comment by kevinearldenny** [comment]
Hmmm, so as I'm digging into this I'm noticing that the `region` field on Organization is a plain text field - so, it may be a bit difficult to filter out to only display organizations that match with the parsed Region of the block file without some changes to [this field ](https://github.com/PublicMapping/districtbuilder/blob/1a78e2b1484e346fa83dca8bbf8614386dcf5d30/src/server/src/organizations/entities/organization.entity.ts#L40)

**Comment by maurizi** [comment]
We shouldn't use the `Organization.region` field - that's just for display in the UI.

We should filter to Organizations which have a _project template_ which matches the state in the CSV, and then additionally filter the list of project templates to that region - e.g. the Dane County organization should be shown for any CSVs with WI data, because the Dane County project template uses `WI` for its `regionCode`.
