### ISSUE TITLE
Washington DC mini maps rendering isn't pretty

### ISSUE THREAD

**Issue by dmcglone** [PublicMapping/districtbuilder#994]
Minimaps on the Washington DC Community Maps page have a rendering issue, see screenshot below:

![image](https://user-images.githubusercontent.com/1688859/131406328-6878d906-eff5-4a33-bd11-db9c668357f0.png)

**Comment by maurizi** [comment]
This is almost certainly due to the simplification we're doing with `turf` before returning this GeoJSON

https://github.com/PublicMapping/districtbuilder/blob/d3138c49316a1545985125f5d76fd34f94fdec21/src/server/src/projects/services/projects.service.ts#L73

DC is quite small compared to most states - I wonder if we need to vary the `tolerance` we use based on a per-region configuration (or maybe dynamically chosen based on region size?)
